classDiagram
	Person <|.. User
	User "1" *-- "1" UserData
	User "1" *-- "0..*" Visitor
	
	class Person {
	<<abstract>>
		+firstName: string
		+lastName: string
		+userID: string
	}

	class User {
		+privledge: int = 0
		+visitors: [ Visitor ]
		+userData: UserData

	}

	class UserData {
		+address: string
		+gender: string
		+birthday: date
		+licensePlate: string
		+email: string
		+phone: number
	}

	class Visitor {
		+ expirationDate: date
		+ licensePlate: string
	}